services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: .
          target: /app
          action: sync
          ignore:
            - node_modules/